"""empty message

Revision ID: 5947c2d1a6db
Revises: 63a3598b7e20
Create Date: 2022-06-30 11:17:04.062543

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '5947c2d1a6db'
down_revision = '63a3598b7e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
